[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emailer"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
    "pydantic==2.6.1",
    "pydantic-settings==2.2.1"
]
authors = [
  {name = "Prometejs Labs", email = "prometejslabs@gmail.com"}
]
maintainers = [
  {name = "Elvis Segbawu", email = "elvissegbawu@gmail.com"}
]
description = "Lovely Spam! Wonderful Spam!"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Development Status :: 4 - Alpha",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
keywords = ["emailer"]

[project.urls]
Homepage = "https://github.com/Prometejs/emailer.git"
Documentation = "https://github.com/Prometejs/emailer.git"
Repository = "https://github.com/Prometejs/emailer/blob/main/README.md"
Issues = "https://github.com/Prometejs/emailer/issues"
Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]
emailer = "__main__:main"

# [tool.setuptools.package-dir]
# "" = "src"

# [tool.setuptools]
# packages = ["src"]
# include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["logging.conf"]

# [project.entry-points.console_scripts]
# emailer = "src.__main__:main"

# [tool.setuptools]
# packages = ["src"]
# include-package-data = true