name: build executables and push to GHCR

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: 
          # - ubuntu-latest
          - windows-latest
        version:
          - '3.10'
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Extract matrix os string
        if: matrix.os == 'windows-latest'
        shell: powershell
        id: extract_os_string-windows
        run: |
          $INPUT_STRING = "${{ matrix.os }}"
          $OUTPUT_STRING = $INPUT_STRING -replace '-latest', ''
          echo "os=$OUTPUT_STRING" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: Extract matrix os string
        if: matrix.os == 'ubuntu-latest'
        id: extract_os_string-linux
        run: |
          INPUT_STRING=${{ matrix.os }}
          OUTPUT_STRING="${INPUT_STRING%-*}"
          echo "os=$OUTPUT_STRING" >> $GITHUB_ENV

      - name: Build Executable Binary
        run: pyinstaller ./src/__main__.py --onefile -p ./src --add-data ./src/logging.conf:. --name emailer

      - name: Install ORAS CLI
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="1.1.0"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
          mkdir -p oras-install/
          tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
          sudo mv oras-install/oras /usr/local/bin/
          rm -rf oras_${VERSION}_*.tar.gz oras-install/
      
      - name: Install ORAS CLI
        if: matrix.os == 'windows-latest'
        run: |
          Set-Variable -Name "VERSION" -Value "1.1.0"
          curl.exe -sLO  "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_windows_amd64.zip"
          tar.exe -xvzf oras_${VERSION}_windows_amd64.zip
          mkdir -p $env:HOMEPATH/.local/bin/
          copy oras.exe $env:HOMEPATH/.local/bin/
          "$env:HOMEPATH/.local/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
                    
      - name: Log in to GitHub Container Registry
        run: |    
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Convert GitHub repository to lowercase
        run: |
          echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Upload ${{ matrix.os }} executables
        run: |
          oras push ghcr.io/${{ env.repository }}/emailer.${{ env.os }}:latest ./dist/emailer:application/vnd.prometejs.${{ steps.extract_os_string.outputs.os }}.bin
          oras push ghcr.io/${{ env.repository }}/emailer.${{ env.os }}:${{ github.sha }} ./dist/emailer:application/vnd.prometejs.${{ steps.extract_os_string.outputs.os }}.bin

      - name: Logout from GitHub Container Registry
        run: oras logout ghcr.io
